server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://gracious-wisdom.railway.internal:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /uploads/ {
        try_files $uri @uploads_backend;
    }
    location @uploads_backend {
        proxy_pass http://gracious-wisdom.railway.internal:8080;
        proxy_set_header Host $host;
    }
}