server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://gracious-wisdom-production-01d2.up.railway.app/api/;
        proxy_set_header Host gracious-wisdom-production-01d2.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_http_version 1.1;
    }
    location /uploads/ {
        try_files $uri @uploads_backend;
    }
    location @uploads_backend {
        proxy_pass http://gracious-wisdom-production-01d2.up.railway.app;
        proxy_set_header Host gracious-wisdom-production-01d2.up.railway.app;
    }
}